builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: binary
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
